#version: '3.5'

services:
  nginx:
    build: infra/nginx
    ports:
      - "8088:8088"
    depends_on:
      - app
  app:
    build: ./
    ports:
      - "8081:8081"
    volumes:
      - ./plugins/TestPlugin:/home/ichat/plugins/TestPlugin
      - ./data:/home/ichat/data
      - ./auth:/home/ichat/auth
