models:
  - name: "gpt-3.5-turbo"
    type: "openai"
    baseUrl: "https://oneapi.xty.app/v1/"
    apiKey: ""
  - name: "gpt-4o-mini"
    type: "openai"
    baseUrl: "https://oneapi.xty.app/v1/"
    apiKey: ""
  - name: "qwen2.5:7b"
    type: "ollama"
    baseUrl: ""
    apiKey: ""
toolModel: "gpt-3.5-turbo"
chatModel: "gpt-3.5-turbo"
adminPwd: "123456"
api:
  enabled: false
  key: "123456"
  port: 8081
ipPool:
  enabled: false
  urls:
    - https://www.proxy-list.download/api/v2/get?l=en&t=http
    - http://api.89ip.cn/tqdl.html?api=1&num=200&port=&address=&isp=
    - https://openproxy.space/list/http
    - http://www.ip3366.net/free/
#    - https://www.kuaidaili.com/free/
#    - https://www.docip.net/free
#    - https://www.zdaye.com/Free/