CREATE TABLE SESSION
(
    ID          INT PRIMARY KEY NOT NULL,
    USERNAME    VARCHAR(255)    NOT NULL,
    LOGIN       TINYINT         NOT NULL,
    CHAT_MODEL  VARCHAR(255),
    IMAGE_MODEL VARCHAR(255),
    TIPS        TEXT,
    STRICT      TINYINT         NOT NULL,
    GPT4MODEL   VARCHAR(255)
)